social/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # importamos ajustes
from django.conf.urls.static import static # importamos archivos estaticos

from .views import HomeView # importar todo de path
from .views import notification_redirect, notifications_delete # importar todo de path

#PARA PDOER CAMBIAR LA IMAGEN DEL ADMIN DE DJANGO
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "HOLA! AQUI PUEDES MODERAR COALSOCIAL"
admin.site.site_title = "MODERAR COALSOCIAL"
admin.site.index_title = "BIENVENIDO AL ADMINISTRADOR DEL COALSOCIAL!"

urlpatterns = [
    path("admin/", admin.site.urls),

    #autenticar usuarios
    path('accounts/', include('allauth.urls')),

    path('users/', include('users.urls')),
    path('social/', include('social.urls')),

    path('', HomeView.as_view(), name='home'),
    #rediurect
    path('post/<str:dato>/<int:notification_id>/', notification_redirect.as_view(), name='notification-redirect'),
    #eliminar notificaiciones
    path('post/<str:user>/', notifications_delete.as_view(), name='notifications-delete'),
]

#PARA QUE PUEDAN FUNCIONAR LOS ARCHIVOS ESTATICOS EN EL MODO DEBUG
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

social/social/urls.py
from django.urls import path
from .views import (
    PostDeleteView, 
    PostDetailView, 
    PostEditView, 
    AddDislike, 
    AddLike, 
    CommentDeleteView, 
    CommentEditView, 
    CommentReplyView,
    AddCommentDislike, 
    AddCommentLike,
    UserSearch,
    #reportes
    AddReport,
    ControlReports,
    ControlPost,

    )


app_name="social"

urlpatterns = [
    path('post/<int:pk>/', PostDetailView.as_view(), name="post-detail"),
    path('post/edit/<int:pk>/', PostEditView.as_view(), name="post-edit"),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name="post-delete"),

    #like dislike y comentarios!
    path('post/<int:pk>/like', AddLike.as_view(), name='like'),
    path('post/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),

    #REPORTES
    path('post/<int:pk>/report', AddReport.as_view(), name='report'),

    #BUESQUEDA DE USUARIOS
    path('share/', UserSearch.as_view(), name='profile-search'),

    #ELIMINAR EDITAR COEMENTARIOS
    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name="comment-delete"),
    path('post/<int:post_pk>/comment/edit/<int:pk>/', CommentEditView.as_view(), name="comment-edit"),

    #DAR LIKE DISLIKE A LOS COMENTARIOS
    path('post/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name="comment-like"),
    path('post/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name="comment-dislike"),

    #RESPONDERA UN COEMNTARIO
    path('post/<int:post_pk>/comment/<int:pk>/reply',CommentReplyView.as_view(), name='comment-reply'),


    #### ADMINISTRAR
    #reportes
    path('Control/Reportes/admin', ControlReports.as_view(), name='ControlReports'),
    #aprobar
    path('Control/Post/admin', ControlPost.as_view(), name='ControlPost'),
]

social/users/urls.py
from django.urls import path

from .views import UserProfileView, EditProfile, AddFollower, RemoveFollower, ListFollowers, EditProfileStatic


app_name="users"

urlpatterns = [
    path('<username>/', UserProfileView.as_view(), name="profile"),
    path('myprofile/edit/', EditProfile, name="edit-profile"),
    path('myprofile/edit/static/', EditProfileStatic, name="edit-profile-static"),

    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
	path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),
    
    path('profile/<int:pk>/followers/',ListFollowers.as_view(), name='followers-list'),

]

social/social/forms.py
from django import forms
from .models import SocialPost, SocialComment, NotificationSocial


class SocialPostForm(forms.ModelForm):
    body = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'rounded-md bg-white border p-2 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 dark:bg-dark-third dark:border-dark-third dark:text-dark-txt flex max-w-full sm:text-sm border-gray-300 rounded-md mx-auto',
            'rows': '3',
            'placeholder': 'Hgosteare...'
        }),
        required=True
    )
    image = forms.FileField(widget=forms.ClearableFileInput(attrs={
        'class': ' hidden',
        'allow_multiple_selected': True,
        'id':'dropzone-file'
        }),
        required=False
        )

    class Meta:
        model = SocialPost
        fields = ['body']

class SocialCommentForm(forms.ModelForm):
    comment = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 dark:bg-dark-third dark:border-dark-third sm:text-sm border-gray-300 rounded-md block w-full block',
            'rows': '1',
            'placeholder': 'Hoy voy a Hgostear...',
            'id': 'comment-holderPrincipal'
            }),
        required=True
        )

    class Meta:
        model=SocialComment
        fields=['comment']


class NotificationSocialForm(forms.ModelForm):  
    mensaje = forms.CharField()
    ##################
    class Meta:
        model=NotificationSocial
        fields=['mensaje']

social/social/views.py
from social.forms import SocialCommentForm, NotificationSocialForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.urls.base import reverse_lazy
from django.views.generic.base import View
from .models import SocialPost, SocialComment, User
from django.views.generic.edit import UpdateView, DeleteView
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from users.models import Profile
from django.http import JsonResponse
import json

#crear un html desde la vista
from django.template import loader

from django.db.models import Q #importar datos de la base de datos
import time

#para poder cambiar el idioma
from django.utils.translation import activate

import datetime



#NOTIFICACIONES
def Notification(userde, userpara, context, ver, request):
    if userde != userpara:
        form = NotificationSocialForm()
        new_notification = form.save(commit=False)
        new_notification.de = userde
        id = int(ver)
        new_notification.post = str(id)
        new_notification.para = userpara
        new_notification.mensaje = context
        new_notification.save()
        return 'EXITOSO'
    else:
        return 'MISMO USUARIO'



#obligar cache
def timestamp():
    return str(int(time.time() * 1000))


class PostDetailView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        activate('es')  # Establece el contexto de traducción en español
        post = SocialPost.objects.get(pk=pk)
        form = SocialCommentForm()

        comments = SocialComment.objects.filter(post=post).order_by('-created_on')

        context = {
            'post': post,
            'form': form,
            'comments':comments
        }

        return render(request, 'pages/social/detail.html', context)

    def post(self, request, pk, *args, **kwargs):
        activate('es')  # Establece el contexto de traducción en español
        post = SocialPost.objects.get(pk=pk)
        form = SocialCommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            ###########################
            userde = request.user
            userpara = post.author
            context = f'{userde} agrego un comentario'
            ver = post.pk
            Notification(userde, userpara, context, ver, request)
            ###########################
            new_comment.save()
        else:
            print(form.errors," ERROR EN LA SOLICITUD DE INTRODUCIR DATOS A LA BASE DE DATOS")

        comment = SocialComment.objects.filter(pk=new_comment.pk).order_by('-created_on')#comentario creado
        context = {
            'post': post,
            'form': form,
            'comments':comment
        }

        html = render(request, 'pages/social/comment_ajax.html', context)
        #print(html) --> TENEMOS EL DOCUEMNTO HTML CORRECTAMENTE!

        comments = SocialComment.objects.filter(post=post).order_by('-created_on')
        comments_data = [{'text': comment.comment, 'author': comment.author.username} for comment in comments]
        html_content = html.content.decode('utf-8')  # Obtener el contenido HTML como una cadena
        #print(html_content) --> LITERALMENTE EL HTML QUE NECESITAMOS RESPONDER!

        response_data = {
            'comments': comments_data,
            'html_generado': html_content,
        }
        return JsonResponse(response_data)



#VISTA DE VIDEOS MULTIMEDIA
class HomeMediaView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):

        posts = SocialPost.objects.all()
        #para ver solamente a los que seguimos:
        img=timestamp()

        user = request.user
        profile = Profile.objects.get(user=user)

        followers = profile.followers.all()
        follow = profile.followers.all()

        if len(followers) == 0:
                is_following = False
            
        for follower in followers:
            if follower == request.user:
                is_following = True
                break
            else:
                is_following = False

        number_of_followers = len(followers)

        context = {
            'user':user,
            'profile':profile,
            'number_of_followers': number_of_followers,
            'is_following': is_following,
            'follow':follow,
            'img':img,
            'posts':posts,
            #notification (poder eliminar) abajo
        }
        return render(request, 'pages/index.html', context)


class PostEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    activate('es')  # Establece el contexto de traducción en español
    model=SocialPost
    fields=['body']
    template_name='pages/social/edit.html'

    def get_success_url(self):
        activate('es')  # Establece el contexto de traducción en español
        pk = self.kwargs['pk']
        return reverse_lazy('social:post-detail', kwargs={'pk':pk})

    def test_func(self):
        activate('es')  # Establece el contexto de traducción en español
        post = self.get_object()
        return self.request.user == post.author



class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    activate('es')  # Establece el contexto de traducción en español
    model=SocialPost
    template_name='pages/social/delete.html'
    success_url = reverse_lazy('home')

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author



class AddLike(LoginRequiredMixin, View):
    activate('es')  # Establece el contexto de traducción en español
    def post(self, request, pk, *args, **kwargs):
        post = SocialPost.objects.get(pk=pk)

        is_dislike = False
        
        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            post.dislikes.remove(request.user)

        is_like = False
        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break
        
        if not is_like:
            userde = request.user
            userpara = post.author
            context = f'a {userde} le gusto tu publicacion'
            ver = post.pk
            Notification(userde, userpara, context, ver, request)
            post.likes.add(request.user)

        if is_like:
            post.likes.remove(request.user)


        like_count = post.likes.count()

        #variable para contar dislikes
        dislike_count = post.dislikes.count()


        # Construir la respuesta en formato JSON
        response_data = {
            'liked': not is_like,
            'like_count': like_count,
            #dislike count
            'dislike_count': dislike_count,
        }

        # Devolver la respuesta JSON
        return JsonResponse(response_data)


class AddDislike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = SocialPost.objects.get(pk=pk)
        activate('es')  # Establece el contexto de traducción en español

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            post.likes.remove(request.user)

        is_dislike = False
        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislikes.add(request.user)

        if is_dislike:
            post.dislikes.remove(request.user)

        dislike_count = post.dislikes.count()

        #contar los likes poara retornar al javascript
        like_count = post.likes.count()



        # Construir la respuesta en formato JSON
        response_data1 = {
            'disliked': not is_dislike,
            'dislike_count': dislike_count,
            #like coun
            'like_count': like_count
        }

        # Devolver la respuesta JSON
        return JsonResponse(response_data1)



class AddCommentLike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        activate('es')  # Establece el contexto de traducción en español
        comment = SocialComment.objects.get(pk=pk)
        post = comment.post

        is_dislikeCom = False
        for dislike in comment.dislikes.all():
            if dislike == request.user:
                is_dislikeCom = True
                break

        if is_dislikeCom:
            comment.dislikes.remove(request.user)

        is_likeCom = False
        for like in comment.likes.all():
            if like == request.user:
                is_likeCom = True
                break
        
        if not is_likeCom:
            userde = request.user##
            userpara = comment.author
            ver = post.pk
            context = f' a {userde} le gusto tu comentario: {comment.comment[:15]}...'##
            Notification(userde, userpara, context, ver, request)##
            comment.likes.add(request.user)

        if is_likeCom:
            comment.likes.remove(request.user)

        comment_dislike_count = comment.dislikes.count()

        #contar los likes poara retornar al javascript
        comment_like_count = comment.likes.count()

        
        # Construir la respuesta en formato JSON
        response_data_Com = {
            'dislike_count': comment_dislike_count,
            'like_count': comment_like_count,
            'liked': not is_likeCom,
        }
        #json_data = json.dumps(response_data_Com)
        #print(json_data)
        return JsonResponse(response_data_Com)


class AddCommentDislike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):

social/templates/pages/social/comment_ajax.html
{% load humanize %}
{% for comment in comments %}
{% if comment.is_parent %}
<a href="{% url 'users:profile' comment.author.username %}">
    <img src="{{comment.author.profile.picture.url}}" alt="Profile picture" class="w-9 h-9 rounded-full">
    </a>
    <div>
        <div class="bg-gray-100 dark:bg-dark-third p-2 rounded-2xl text-sm">
            
            <a href="{% url 'users:profile' username=post.author.username %}" class="font-semibold block hover:text-blue-500 dark:text-dark-txt"><p>{{comment.author}}</p></a>
            
            <span class="dark:text-dark-txt">{{comment.comment}}</span>
            <span class="text-xs dark:text-dark-txt text-gray-500 float-right">{{comment.created_on | naturaltime}}</span>
        </div>
        

        <div x-data="{open:false}" class=" text-xs text-gray-500 dark:text-dark-txt">
            {% if request.user == comment.author %}
                <a href="{% url 'social:comment-edit' post.pk comment.pk %}" class="font-semibold cursor-pointer text-sm text-green-500">
                    <!--edit comment-->
                    <i class="bx bx-edit w-5" ></i>
                </a>
                <a href="{% url 'social:comment-delete' post.pk comment.pk %}" class="font-semibold cursor-pointer text-sm text-red-500">
                    <!-- delete comment-->
                    <i class="bx bx-trash" ></i>
                </a>
            {% endif %}
            <form method="POST" action="{% url 'social:comment-like' post.pk comment.pk %}" class="pl-2 inline-flex">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{request.path}}">

                <!--BOTON DE COMENTARIOS APRA DAR LIKE -->
                {% if request.user in comment.likes.all %}
                    <button id="like-btn-comment-{{ comment.pk }}" data-comment-id="{{ comment.pk }}" data-post-id="{{ post.pk }}" data-like-url="{% url 'social:comment-like' post.pk comment.pk %}" type="submit" class="comment-like-btn flex space-x-2 justify-center items-center text-xs py-2 rounded-lg cursor-pointer text-blue-600  flex space-x-2 justify-center items-center text-xl py-2 rounded-lg cursor-pointer text-blue-600">
                {% else %}   
                    <button id="like-btn-comment-{{ comment.pk }}" data-comment-id="{{ comment.pk }}" data-post-id="{{ post.pk }}" data-like-url="{% url 'social:comment-like' post.pk comment.pk %}" type="submit" class="comment-like-btn flex space-x-2 justify-center items-center text-xs py-2 rounded-lg cursor-pointer text-black-600ss "> 
                {% endif %}
                <i class='bx bx-like'></i><p class="text-sm font-semibold">{{comment.likes.all.count}}</p>
                </button>
            </form>

            <form method="POST" action="{% url 'social:comment-dislike' post.pk comment.pk %}" class="pl-2 inline-flex">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{request.path}}">

                <!--BOTON DE COMENTARIOS APRA DAR DISLIKE -->
                {% if request.user in comment.dislikes.all %}
                    <button id="dislike-btn-comment-{{ comment.pk }}" data-comment-id="{{ comment.pk }}" data-post-id="{{ post.pk }}" data-dislike-url="{% url 'social:comment-dislike' post.pk comment.pk %}" type="submit" class="comment-dislike-btn flex space-x-2 justify-center items-center text-xs py-2 rounded-lg cursor-pointer text-blue-600  flex space-x-2 justify-center items-center text-xl py-2 rounded-lg cursor-pointer text-red-500">
                {% else %}   
                    <button id="dislike-btn-comment-{{ comment.pk }}" data-comment-id="{{ comment.pk }}" data-post-id="{{ post.pk }}" data-dislike-url="{% url 'social:comment-dislike' post.pk comment.pk %}" type="submit" class="comment-dislike-btn flex space-x-2 justify-center items-center text-xs py-2 rounded-lg cursor-pointer text-black-600ss "> 
                {% endif %}
                <i class='bx bx-dislike'></i><p class="text-sm font-semibold">{{comment.dislikes.all.count}}</p>
                </button>
            </form>


            <button @click="open = true" class="inline-flex space-x-2 justify-center items-center text-xs py-2 rounded-lg cursor-pointer text-gray-500 dark:text-dark-txt">
            <i class='ml-2 bx bx-comment'></i><p class="text-sm font-semibold">{{ comment.children.count }}
            </p>
            </button>

            <!-- This example requires Tailwind CSS v2.0+ -->
            <div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" @click.away="open = false" class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
                <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">

                    <div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" x-description="Background overlay, show/hide based on modal state." class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" @click="open = false" aria-hidden="true"></div>


                    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

                    <div class="inline-block align-bottom dark:bg-dark-second dark:text-dark-txt bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-sm sm:w-full sm:p-6">
                    <div>
                        
                        <div class="mt-3 text-center sm:mt-5">
                        <h3 class="text-lg leading-6 font-medium dark:text-dark-txt text-gray-900" id="modal-title">
                            Responde a un comentario!
                        </h3>
                        <div class="mt-2">
                            <p class="text-sm text-gray-500 dark:text-dark-txt">
                            Que opinas de este comentario? <br>
                            Recuerda que tu conducta tiene consecuenias.
                            </p>
                        </div>
                        
                        <div class="mt-5 sm:mt-6 ">
                        {% comment %} <label class="block text-sm font-medium dark:text-dark-txt text-gray-700">
                            Body
                        </label> {% endcomment %}
                        <form method="POST" id="formulario-{{comment.pk}}" action="{% url 'social:comment-reply' post.pk comment.pk %}" class="inline-flex flex-col">
                            {% csrf_token %}
                            {{form.comment}}
                            <div class="block mt-2">
                                <button @click="open = false" formCommentID="formulario-{{comment.pk}}" DivReply="comment-children-{{ comment.pk }}" data-reply-comment="{% url 'social:comment-reply' post.pk comment.pk %}" id="{{comment.pk}}" type="submit" class="CommentReplyAllBtn inline-flex justify-center w-full rounded-md border border-transparent shadow-sm px-4 py-2 bg-green-600 text-base font-medium text-white hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 sm:text-sm">
                                    PUBLICAR
                                </button>
                                <a @click="open = false" type="button" class="mtinline-flex justify-center w-full rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:text-sm mt-2">
                                    SALIR
                                </a>
                            </div>
                        </form>
                        
                    </div>

                        </div>
                    </div>
                    </div>
                </div>
            </div>

            
            
        </div>
        
        <!-- REPLY COMMENT -->
        <div id="comment-children-{{ comment.pk }}">
        {% for comment in comment.children %}
        
        <div class="flex space-x-2" >
            <a href="{% url 'users:profile' comment.author.username %}">
            <img src="{{comment.author.profile.picture.url}}" alt="Profile picture" class="w-9 h-9 rounded-full">
            </a>
            <div>
                <div class="bg-gray-100 dark:bg-dark-third p-2 rounded-2xl text-sm">
                    <a href="{% url 'users:profile' username=post.author.username %}" class="font-semibold block hover:text-blue-500 dark:text-dark-txt"><p>{{comment.author}}</p></a>
                    <span class="dark:text-dark-txt">{{comment.comment}}</span>
                <span class="text-xs dark:text-dark-txt text-gray-500 float-right">{{comment.created_on | naturaltime}}</span>
                </div>
                <div class="p-2 text-xs text-gray-500 dark:text-dark-txt">
                    {% if request.user == comment.author %}
                        <a href="{% url 'social:comment-edit' post.pk comment.pk %}" class="font-semibold cursor-pointer text-sm text-green-500">
                            <!--edit comment-->
                            <i class="bx bx-edit w-5" ></i>
                        </a>
                        <a href="{% url 'social:comment-delete' post.pk comment.pk %}" class="font-semibold cursor-pointer text-sm text-red-500">
                            <!-- delete comment-->
                            <i class="bx bx-trash" ></i>
                        </a>
                    {% endif %}

                    <form method="POST" class="pl-2 inline-flex">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{request.path}}">

                        <!--BOTON DE COMENTARIOS APRA DAR LIKE -->
                        {% if request.user in comment.likes.all %}
                            <button id="like-btn-comment-{{ comment.pk }}" data-comment-id="{{ comment.pk }}" data-post-id="{{ post.pk }}" data-like-url="{% url 'social:comment-like' post.pk comment.pk %}" type="submit" class="comment-like-btn flex space-x-2 justify-center items-center text-xs py-2 rounded-lg cursor-pointer text-blue-600  flex space-x-2 justify-center items-center text-xl py-2 rounded-lg cursor-pointer text-blue-600">
                        {% else %}   
                            <button id="like-btn-comment-{{ comment.pk }}" data-comment-id="{{ comment.pk }}" data-post-id="{{ post.pk }}" data-like-url="{% url 'social:comment-like' post.pk comment.pk %}" type="submit" class="comment-like-btn flex space-x-2 justify-center items-center text-xs py-2 rounded-lg cursor-pointer text-black-600ss "> 
                        {% endif %}
                        <i class='bx bx-like'></i><p class="text-sm font-semibold">{{comment.likes.all.count}}</p>
                        </button>
                    </form>


                    <form method="POST" action="{% url 'social:comment-dislike' post.pk comment.pk %}" class="pl-2 inline-flex">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{request.path}}">

                        <!--BOTON DE COMENTARIOS APRA DAR DISLIKE -->
                        {% if request.user in comment.dislikes.all %}
                            <button id="dislike-btn-comment-{{ comment.pk }}" data-comment-id="{{ comment.pk }}" data-post-id="{{ post.pk }}" data-dislike-url="{% url 'social:comment-dislike' post.pk comment.pk %}" type="submit" class="comment-dislike-btn flex space-x-2 justify-center items-center text-xs py-2 rounded-lg cursor-pointer text-blue-600  flex space-x-2 justify-center items-center text-xl py-2 rounded-lg cursor-pointer text-red-500">
                        {% else %}   
                            <button id="dislike-btn-comment-{{ comment.pk }}" data-comment-id="{{ comment.pk }}" data-post-id="{{ post.pk }}" data-dislike-url="{% url 'social:comment-dislike' post.pk comment.pk %}" type="submit" class="comment-dislike-btn flex space-x-2 justify-center items-center text-xs py-2 rounded-lg cursor-pointer text-black-600ss "> 
                        {% endif %}
                        <i class='bx bx-dislike'></i><p class="text-sm font-semibold">{{comment.dislikes.all.count}}</p>
                        </button>
                    </form>

                </div>
            </div>
        </div> 
        
    {% endfor %}
    </div>    
        <!-- END REPLY COMMENT -->
    </div>
{% endif %}
{% endfor %}

social/templates/pages/social/search.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}


{% block left_sidebar %}
{% include 'components/sidebars/left/sidebar.html' %}
{% endblock left_sidebar %}


  {% block content %}
<div class="w-full mx-auto lg:w-3/4 xl:w-3/5 mt-8 px-2"> 
    <div class="grid sm:grid-cols-3 grid-cols-2 gap-4 ">


      {% for user in profile_list %}
      <div class="grid grid-cols-1">
        <div class="col-span-1 bg-gray-200 dark:bg-black rounded-md">
          <div class="bg-white m-1 overflow-hidden shadow-md dark:bg-dark-second">
            <div class="top pt-5">
              <img src="{{ user.picture.url }}?{{img}}" alt="Profile picture" class="w-24 h-24 rounded-full mx-auto border-4">
            </div>
            <h6 class="dark:text-dark-txt text-center text-1xl font-sans font-medium pt-1"> <b>{{ user.user.username }} </b> </h6>
            <h6 class=" dark:text-dark-txt text-center text-1xl font-sans font-medium pt-1 pb-5">
              {% if user.user.profile.name == none %}
                sin nombre...
              {% else %}
                {{ user.user.profile.name }}  
              {% endif %}
            </h6>
            <div class="w-2/3 mx-auto">
              <a href="{% url 'users:profile' user.user.username %}" class=" bg-orange-500 text-white px-4 py-1 mb-5 text-center rounded-md mx-auto block w-70">
                Ver
              </a>
            </div>
          </div>
        </div>
      </div>
      

        
      {% endfor %}
    
    </div>
</div>
  {% endblock content %}



{% block right_sidebar %}
{% endblock right_sidebar %}



{% block footer %}
{% endblock footer %}

{% block javascript %}{% endblock javascript %}