social/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # importamos ajustes
from django.conf.urls.static import static # importamos archivos estaticos

from .views import HomeView # importar todo de path
from .views import notification_redirect, notifications_delete # importar todo de path

#PARA PDOER CAMBIAR LA IMAGEN DEL ADMIN DE DJANGO
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "HOLA! AQUI PUEDES MODERAR COALSOCIAL"
admin.site.site_title = "MODERAR COALSOCIAL"
admin.site.index_title = "BIENVENIDO AL ADMINISTRADOR DEL COALSOCIAL!"

urlpatterns = [
    path("admin/", admin.site.urls),

    #autenticar usuarios
    path('accounts/', include('allauth.urls')),

    path('users/', include('users.urls')),
    path('social/', include('social.urls')),

    path('', HomeView.as_view(), name='home'),
    #rediurect
    path('post/<str:dato>/<int:notification_id>/', notification_redirect.as_view(), name='notification-redirect'),
    #eliminar notificaiciones
    path('post/<str:user>/', notifications_delete.as_view(), name='notifications-delete'),
]

#PARA QUE PUEDAN FUNCIONAR LOS ARCHIVOS ESTATICOS EN EL MODO DEBUG
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

social/social/urls.py
from django.urls import path
from .views import (
    PostDeleteView, 
    PostDetailView, 
    PostEditView, 
    AddDislike, 
    AddLike, 
    CommentDeleteView, 
    CommentEditView, 
    CommentReplyView,
    AddCommentDislike, 
    AddCommentLike,
    UserSearch,
    #reportes
    AddReport,
    ControlReports,
    ControlPost,

    )


app_name="social"

urlpatterns = [
    path('post/<int:pk>/', PostDetailView.as_view(), name="post-detail"),
    path('post/edit/<int:pk>/', PostEditView.as_view(), name="post-edit"),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name="post-delete"),

    #like dislike y comentarios!
    path('post/<int:pk>/like', AddLike.as_view(), name='like'),
    path('post/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),

    #REPORTES
    path('post/<int:pk>/report', AddReport.as_view(), name='report'),

    #BUESQUEDA DE USUARIOS
    path('share/', UserSearch.as_view(), name='profile-search'),

    #ELIMINAR EDITAR COEMENTARIOS
    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name="comment-delete"),
    path('post/<int:post_pk>/comment/edit/<int:pk>/', CommentEditView.as_view(), name="comment-edit"),

    #DAR LIKE DISLIKE A LOS COMENTARIOS
    path('post/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name="comment-like"),
    path('post/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name="comment-dislike"),

    #RESPONDERA UN COEMNTARIO
    path('post/<int:post_pk>/comment/<int:pk>/reply',CommentReplyView.as_view(), name='comment-reply'),


    #### ADMINISTRAR
    #reportes
    path('Control/Reportes/admin', ControlReports.as_view(), name='ControlReports'),
    #aprobar
    path('Control/Post/admin', ControlPost.as_view(), name='ControlPost'),
]

social/templates/components/footer.html
{% load static %}
<div class="mt-auto p-6 text-sm text-gray-500 dark:text-dark-txt">
    
    <a href="#">Privacidad</a>
    <span>.</span>
    <a href="#">Terminos</a>
    <span>.</span>
    <a href="#">Puntos</a>
    <span>.</span>

    {% if user.is_authenticated %}
    <a class="hover:underline" href="{% url 'account_logout' %}">Logout</a>
    {% endif %}


    <p class="cursor-default text-xs text-gray-100 dark:text-dark-txt">Hgost &copy; 2024</p>
</div>

social/templates/components/navbar.html
{% load static %}
<nav class="bg-white dark:bg-dark-second h-max md:h-14 w-full shadow flex flex-col md:flex-row items-center justify-center md:justify-between fixed top-0 z-20 border-b dark:border-dark-third">

    <!-- LEFT NAV -->
    <div class="flex items-center justify-between w-full md:w-max px-4 py-2">
        <a href="{% url 'home' %}" class="mr-2 hidden md:inline-block">
            <img src="{% static 'img/logo.png' %}"  class="w-24 sm:w-20 lg:w-10 h-auto">
        </a>
        <a href="{% url 'home' %}" class="inline-block md:hidden">
            <img src="{% static 'img/logo.png' %}" alt="" class="w-10 h-10">
        </a>

        <div class="flex items-center justify-between space-x-1">

        {% if not user.is_authenticated %}

                <a href="{% url 'account_login' %}" class="inline-flex md:hidden items-center justify-center p-1 rounded-full bg-orange-600 hover:bg-orange-600 dark:hover:bg-dark-third mx-1">
                    <span class="mx-2 font-semibold dark:text-dark-txt">Ingresar</span>
                </a>

                <a href="{% url 'account_signup' %}" class="inline-flex md:hidden items-center justify-center p-1 rounded-full bg-orange-600 hover:bg-orange-200 dark:hover:bg-dark-third mx-1">
                    <span class="mx-2 font-semibold dark:text-dark-txt">Registrarte</span>
                </a>

        {% else %}
            <a href="#" class="inline-flex md:hidden items-center justify-center p-1 rounded-full hover:bg-gray-200 dark:hover:bg-dark-third mx-1">
                <i class='p-2 bg-orange-600 rounded-full'></i>
                <span class="mx-2 font-semibold dark:text-dark-txt">{{ user.profile.coins }}</span>
            </a>


                <form method="GET" action="{% url 'social:profile-search' %}" class="relative bg-gray-100 dark:bg-dark-third px-2 py-2 w-10 h-10 sm:w-11 sm:h-11 lg:h-10 lg:w-10 xl:w-max xl:pl-3 xl:pr-8 rounded-full flex items-center justify-center cursor-pointer mt-4">
                    <button type="submit" class='bx bx-search-alt-2 text-xl xl:mr-2 dark:text-dark-txt'></button>
                    <!-- NAME = QUERY (ESTO ESTAMOS BUSCANDO DESDE EL VIEW) -->
                    <!-- VALUE = QUERY (ESTO ESTAMOS BUSCANDO DESDE EL VIEW) -->
                    <input name="query" value="{{ request.GET.query }}" type="text" placeholder="Buscar usuarios" class="outline-none border-none bg-transparent hidden xl:inline-block dark:text-white focus:ring-0">
                </form>

        <div x-data="{open:false}">
            <div @click="open=true" class="relative text-xl grid place-items-center md:hidden bg-gray-200 dark:bg-dark-third rounded-full w-10 h-10 cursor-pointer hover:bg-gray-300 dark:text-dark-txt" id="dark-mode-toggle-mb">
                <i class='bx bxs-bell'></i>
                <span class="absolute top-0 right-0 bg-red-500 text-white font-semibold rounded-full px-1 text-center text-xs">{{SocialNotification.count}}</span>
            </div>


            <style>
                /* Estilos personalizados para la barra de desplazamiento */
                .notification-container::-webkit-scrollbar {
                  width: 8px; /* Ancho de la barra de desplazamiento */
                }
              
                .notification-container::-webkit-scrollbar-thumb {
                  background-color: #888; /* Color del pulgar de la barra de desplazamiento */
                }
            </style>


<div x-show="open" @click.away="open=false" class="origin-top-right right-0 mt-2 w-56 rounded-md shadow-lg dark:bg-dark-second bg-white ring-1 ring-black ring-opacity-5 focus:outline-none fixed z-10" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
    <div class="py-1" role="none">
  
      <div class="notification-container max-h-48 overflow-y-auto md:max-h-full" style="max-height: 300px; overflow-y: auto;">
  
        <p href="#" class="text-gray-700 dark:text-dark-txt block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">
          {% if SocialNotification.count != 0 %}
          <a href="{% url 'notifications-delete' user=request.user.id %} " class="text-orange-500 border-b border-orange-500">
            eliminar todas las notificaciones
          </a>
          {% else %}
          No hay notificaciones
          {% endif %}
        </p>
  
        {% for notification in SocialNotification %}
        <p href="#" class="text-gray-700 dark:text-dark-txt block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">
          <img src="{{ notification.de.profile.picture.url }}?{{img}}" alt="Profile picture" class="w-10 h-10 rounded-full inline-block">
          {{notification.mensaje}}
          <a href="{% url 'notification-redirect' dato=notification.post notification_id=notification.id %} " class="text-orange-500 border-b border-orange-500">
            ver
          </a>
        </p>
        {% endfor %}
      </div>
  
    </div>
  </div>
  

        </div>

            
            {% endif %}
        </div>
    </div>
    <!-- END LEFT NAV -->

    <!-- MAIN NAV -->
    <ul x-data="{ open: false }" class="flex w-full lg:w-max items-center justify-center">
        <li class="w-1/5 md:w-max text-center">
            <a href="{% url 'home' %}" class="w-full text-3xl py-2 px-3 xl:px-12 cursor-pointer text-center inline-block text-orange-500 border-b-4 border-orange-600">
                <i class='bx bxs-home'></i>
            </a>
        </li>
        <li class="w-1/5 md:w-max text-center">
            <a href="#" class="w-full text-3xl py-2 px-3 xl:px-12 cursor-pointer text-center inline-block rounded text-gray-600 hover:bg-gray-100 dark:hover:bg-dark-third dark:text-dark-txt relative">
                <i class='bx bx-movie-play'></i>
                {% comment %} <span class="text-xs absolute top-0 right-1/4 bg-red-500 text-white font-semibold rounded-full px-1 text-center">9+</span> {% endcomment %}
            </a>
        </li>
        <li class="w-1/5 md:w-max text-center">
            <a href="#" class="w-full text-3xl py-2 px-3 xl:px-12 cursor-pointer text-center inline-block rounded text-gray-600 hover:bg-gray-100 dark:hover:bg-dark-third dark:text-dark-txt relative">
                <i class='bx bx-store'></i>
            </a>
        </li>
        <li class="w-1/5 md:w-max text-center">
            <a href="#" class="w-full text-3xl py-2 px-3 xl:px-12 cursor-pointer text-center inline-block rounded text-gray-600 hover:bg-gray-100 dark:hover:bg-dark-third dark:text-dark-txt relative">
                <i class='bx bx-group'></i>
            </a>
        </li>
        <li class="w-1/5 md:w-max text-center hidden md:inline-block">
            <button @click="open=true" class="w-full text-3xl py-2 px-3 xl:px-12 cursor-pointer text-center inline-block rounded text-gray-600 hover:bg-gray-100 dark:hover:bg-dark-third dark:text-dark-txt relative">
                <i class='bx bx-menu'></i>
            </button>
        </li>
        <li class="w-1/5 md:w-max text-center inline-block md:hidden">
            <button @click="open=true" class="w-full text-3xl py-2 px-3 xl:px-12 cursor-pointer text-center inline-block rounded text-gray-600 hover:bg-gray-100 dark:hover:bg-dark-third dark:text-dark-txt relative">
                <i class='bx bx-menu'></i>
            </button>
        </li>
    

        <!--LEFT Mobile Sidebar-->
        <div @keydown.window.escape="open = false" x-show="open" aria-labelledby="slide-over-title" x-ref="dialog" aria-modal="true" 
                class="fixed z-10 inset-0 overflow-auto xl:hidden ">
            <div class="absolute inset-0 overflow-hidden">
                
                <div x-description="Background overlay, show/hide based on slide-over state." class="absolute inset-0" @click="open = false" aria-hidden="true"></div>

                <div class="fixed inset-y-0 right-0 pl-10 max-w-full flex ">
                
                    <div x-show="open" @click.away="open = false"  class="w-screen max-w-md" x-description="Slide-over panel, show/hide based on slide-over state.">
                        <div class="h-full flex flex-col py-6 bg-white dark:bg-dark-second shadow-xl overflow-y-scroll scrollbar-hide">
                            <div class="px-4 sm:px-6">
                                <div class="flex items-start justify-between">
                                    <h2 class="text-lg font-medium dark:text-gray-500 text-gray-900" id="slide-over-title">
                                    Menu
                                    </h2>
                                    <div class="ml-3 h-7 flex items-center">
                                    <button class="bg-white dark:bg-dark-third rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" @click="open = false">
                                        <span class="sr-only">Close panel</span>
                                        <svg class="h-6 w-6" x-description="Heroicon name: outline/x" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                                        </svg>
                                    </button>
                                    </div>
                                </div>
                            </div>

                            <div class="mt-6 relative flex-1 px-4 sm:px-6">
                                <!-- Replace with your content -->
                                
                                <!--Menu Items-->
                                {% include 'components/sidebars/left/items.html' %}
                               

                                {% include 'components/footer.html' %}
                                
                                <!-- /End replace -->
                            </div>
                        </div>
                    </div>
                
                </div>
            </div>
        </div>

    </ul>
    <!-- END MAIN NAV -->

    <!-- RIGHT NAV -->
    <ul class="hidden md:flex mx-4 items-center justify-center">

        {% if not user.is_authenticated %}
            <a href="{% url 'account_login' %}" class="inline-flex items-center justify-center p-1 rounded-full bg-orange-600 hover:bg-orange-600 dark:hover:bg-dark-third mx-1">
                <span class="mx-2 font-semibold dark:text-dark-txt">Ingresar</span>
            </a>
        

            <a href="{% url 'account_signup' %}" class="inline-flex items-center justify-center p-1 rounded-full bg-orange-600 hover:bg-orange-200 dark:hover:bg-dark-third mx-1">
                <span class="mx-2 font-semibold dark:text-dark-txt">Registrate</span>
            </a>
        {% else %}

        <li class="h-full xl:flex">
            <a href="#" class="inline-flex items-center justify-center p-1 rounded-full hover:bg-gray-200 dark:hover:bg-dark-third mx-1">
                <i class='p-2 bg-orange-600 rounded-full'></i>
                <span class="mx-2 font-semibold dark:text-dark-txt">{{ user.profile.coins }}</span>
            </a>
        </li>

        <li>
            <div x-data="{open:false}">
            <div @click="open=true" class="text-xl grid place-items-center bg-gray-200 dark:bg-dark-third dark:text-dark-txt rounded-full mx-1 p-3 cursor-pointer hover:bg-gray-300 relative">
                <i class='bx bxs-bell'></i>
                <span class="text-xs absolute top-0 right-0 bg-red-500 text-white font-semibold rounded-full px-1 text-center">{{SocialNotification.count}}</span>
            </div>

            <div x-show="open" @click.away="open=false" class="origin-top-right right-0 mt-2 w-64 rounded-md shadow-lg dark:bg-dark-second bg-white ring-1 ring-black ring-opacity-5 focus:outline-none fixed z-10" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                <div class="py-1" role="none">
              
                  <div class="notification-container max-h-48 overflow-y-auto md:max-h-full" style="max-height: 300px; overflow-y: auto;">
              
                    <p href="#" class="text-gray-700 dark:text-dark-txt block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">
                      {% if SocialNotification.count != 0 %}
                      <a href="{% url 'notifications-delete' user=request.user.id %} " class="text-orange-500 border-b border-orange-500">
                        eliminar todas las notificaciones
                      </a>
                      {% else %}
                      No hay notificaciones
                      {% endif %}
                    </p>
              
                    {% for notification in SocialNotification %}
                    <p href="#" class="text-gray-700 dark:text-dark-txt block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">
                      <img src="{{ notification.de.profile.picture.url }}?{{img}}" alt="Profile picture" class="w-10 h-10 rounded-full inline-block">
                      {{notification.mensaje}}
                      <a href="{% url 'notification-redirect' dato=notification.post notification_id=notification.id %} " class="text-orange-500 border-b border-orange-500">
                        ver
                      </a>
                    </p>
                    {% endfor %}
                  </div>
              
                </div>
            </div>

        </li>
        {% endif %}
    </ul>
    <!-- END RIGHT NAV -->

</nav>